# Generated by Django 6.1 on 2026-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Las Manolas', max_length=80, verbose_name='nombre del sitio')),
                ('tagline', models.CharField(blank=True, default='Ropita linda y cómoda para bebés, niños y adolescentes.', max_length=160, verbose_name='bajada')),
                ('whatsapp_number', models.CharField(help_text='Formato internacional, solo números. Ej: 5491122334455', max_length=20, verbose_name='WhatsApp')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de compra desde el cual el envío es gratis. Vacío = nunca gratis automático.', max_digits=10, null=True, verbose_name='envío gratis a partir de')),
                ('flat_shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Se cobra cuando el pedido no llega al monto de envío gratis.', max_digits=10, verbose_name='costo de envío fijo')),
                ('bank_transfer_info', models.TextField(blank=True, help_text='CBU, alias y titular. Se muestra en el checkout cuando el cliente elige "Transferencia".', verbose_name='datos para transferencia')),
                ('cash_payment_info', models.TextField(blank=True, help_text='Ej: dirección/horario de retiro, o cómo se coordina el pago en efectivo.', verbose_name='instrucciones para efectivo')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
    ]
