# Generated by Django 6.1 on 2026-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='flat_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='free_shipping_threshold',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='courier_cost',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Costo fijo que se muestra y cobra en el checkout para la opción "Mensajería (Andreani)". El envío propio (La Plata / Magdalena y alrededores) se coordina aparte con el cliente, no tiene costo fijo acá.', max_digits=10, verbose_name='costo de mensajería (Andreani)'),
        ),
    ]
