# Generated by Django 6.1 on 2026-08-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='color')),
                ('hex_code', models.CharField(blank=True, help_text='Opcional, para pintar un swatch. Ej: #F6D2DE', max_length=7, verbose_name='código hex')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='talle')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'talle',
                'verbose_name_plural': 'talles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('parent', models.ForeignKey(blank=True, help_text='Vacío = es una sección principal (Bebés/Niños/Adolescentes). Completo = es una subcategoría por prenda dentro de esa sección.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='sección')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['parent_id', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Completalo solo si está en oferta: se muestra tachado arriba del precio actual.', max_digits=10, null=True, verbose_name='precio anterior')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicado')),
                ('is_featured', models.BooleanField(default=False, help_text='Aparece en la home.', verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('category', models.ForeignKey(help_text='La subcategoría por prenda (no la sección).', limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='subcategoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=140, verbose_name='texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size', verbose_name='talle')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes (talle / color / stock)',
                'ordering': ['size__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_category_slug_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_variant_per_product'),
        ),
    ]
