# Generated by Django 6.1 on 2026-08-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('sky', 'Celeste'), ('lilac', 'Violeta'), ('blush', 'Rosa'), ('mint', 'Menta'), ('amber', 'Mostaza')], default='lilac', help_text='Solo se usa para las secciones principales (las cards del home).', max_length=10, verbose_name='color'),
        ),
    ]
