# Generated by Django 6.1 on 2026-08-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#A97FDE', help_text='Color libre de la card en el home. Solo se usa en las secciones principales.', max_length=7, verbose_name='color'),
        ),
    ]
