# Generated by Django 6.1 on 2026-08-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Vacío = foto general (se muestra con cualquier color elegido).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='catalog.color', verbose_name='color'),
        ),
    ]
