# Generated by Django 6.1 on 2026-08-26 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=140, verbose_name='nombre y apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='localidad')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='código postal')),
                ('notes', models.TextField(blank=True, verbose_name='notas del pedido')),
                ('payment_method', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('cash', 'Efectivo'), ('transfer', 'Transferencia')], max_length=20, verbose_name='método de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('mp_preference_id', models.CharField(blank=True, max_length=80, verbose_name='MP preference id')),
                ('mp_payment_id', models.CharField(blank=True, max_length=80, verbose_name='MP payment id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140, verbose_name='producto')),
                ('size_name', models.CharField(blank=True, max_length=20, verbose_name='talle')),
                ('color_name', models.CharField(blank=True, max_length=40, verbose_name='color')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'ítem de pedido',
                'verbose_name_plural': 'ítems de pedido',
            },
        ),
    ]
