# Generated by Django 6.1 on 2026-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Envío (La Plata / Magdalena y alrededores)'), ('courier', 'Mensajería (Andreani)')], default='shipping', max_length=20, verbose_name='método de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(blank=True, choices=[('la_plata', 'La Plata'), ('magdalena', 'Magdalena y alrededores')], max_length=20, verbose_name='zona de envío'),
        ),
    ]
