# Generated by Django 6.1 on 2026-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stock_deducted_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Envío (La Plata / Magdalena y alrededores)'), ('courier', 'Andreani')], default='shipping', max_length=20, verbose_name='método de entrega'),
        ),
    ]
